### ISSUE TITLE
[Flow] Player controls are cross(?)-shaped instead of vertical

### ISSUE THREAD

**Issue by capolpo** [morpheusthewhite/spicetify-themes#1101]
**Describe the bug**
The player controls aren't displaying properly.

**Expected behavior**
For the player controls to display vertically like in the preview images of the theme.

**Screenshots**
![Screenshot (897)](https://github.com/user-attachments/assets/ab291b4b-ee3e-40b1-8b22-cbe66683077e)

**Comment by DavidRaveloU** [comment]
1. Install the CSS Editor extension.
2. Press F12 to open the editor.
3. Paste the following code:

```css
.spotify__container--is-desktop:not(.fullscreen) body::after {
    content: "";
    position: absolute;
    right: 0;
    z-index: 999;
    backdrop-filter: brightness(2.12);
    /* page zoom [ctrl][+] or [ctrl][-]
       edit width and height accordingly */
    width: 135px;
    /* depending on what global status bar
       style is enabled height need to be
       changed accordingly. */
    Height: 40px;
}
```

> [!IMPORTANT]
> To get it right, you need to adjust the height and width until you find the desired fit.
