### ISSUE TITLE
[Feature request] Return the timestamps on the seek bar

### ISSUE THREAD

**Issue by Jnss98b** [morpheusthewhite/spicetify-themes#325]
This theme completely removes the current track progression time and the track length from spotify and it gets annoying sometimes. You should return it but also I recommend a little **_(optional)_** polish where it hides normally and then appears when you hover over the seek bar (as demonstrated below)

**Screenshots**

What it looks like on regular spotify
![image](https://user-images.githubusercontent.com/24306400/115262156-45eb7f00-a102-11eb-8ab9-476ffdc028a2.png)

My suggestion concept
![image](https://user-images.githubusercontent.com/24306400/115262676-c01c0380-a102-11eb-8ac7-3482ed2d6dd7.png)
![image](https://user-images.githubusercontent.com/24306400/115263187-3587d400-a103-11eb-8ac2-3e686b5172a7.png)

**Specifics (please complete the following information):**
 - OS: Windows 10 20H2
 - Spotify version 1.1.56.595.g2d2da0de
 - Spicetify version 1.2.1
 - Theme: DribbblishDynamic

**Comment by peterbrejassou** [comment]
You can add this lines on your user.css :
```
#player-text-elapsed,
#player-text-remaining {
    display: block;
}
#player-text-elapsed{
    margin-right: 0;
    margin-left: 15px;
}
```

The result is like this : 
![image](https://user-images.githubusercontent.com/32335133/115518900-fa171200-a288-11eb-80b8-4dd2c72a8c28.png)

**Comment by JulienMaille** [comment]
I, too, would like to bring back the timer in the theme, but it's difficult to find a place where it doesn't look too ugly.
You can try this, closer to your mockup.
```css

#player-text-remaining {
    display: block;
    position: absolute;
    right: -8px;
    margin-top: 10px;
    color: var(--modspotify_main_fg);
}

#player-text-elapsed{
    display: block;
    position: absolute;
    left: 4px;
    margin-top: 10px;
    color: var(--modspotify_main_fg);
}
```
![image](https://user-images.githubusercontent.com/182520/115623689-cfb16d00-a2f9-11eb-9aa8-1e0dee048b61.png)
