### ISSUE TITLE
[V2] Remove Upgrade button and other bloat components from the new UI

### ISSUE THREAD

**Issue by system32uwu** [morpheusthewhite/spicetify-themes#419]
Easily adding
```css
.upgrade-button, button[data-menu-item="upgrade-account"], .main-contextMenu-menuItem a[href="https://www.spotify.com/premium/"], button[id="upgradeAccount"] {
  display: none !important;
}
```
we could get rid of the Upgrade button in every theme.
[This theme](https://github.com/Daksh777/SpotifyNoPremium/blob/main/user.css) removes other bloat UI components like this one. In case it's not considered worth adding, we should at least include a reference in the README to it.
