### ISSUE TITLE
Dribbblish v2 UI issue when listening on another device

### ISSUE THREAD

**Issue by LuomingXu** [morpheusthewhite/spicetify-themes#440]
**Screenshots**

![image](https://user-images.githubusercontent.com/24503603/124091095-0dfca280-da88-11eb-8df0-25bb2c3c8b87.png)

**Problem**
As you can see, when I use another desktop to listen, the timeline across the song cover.

**Specifics (please complete the following information):**
 - OS: win 21H1
 - Spotify version 1.1.62.583.gdac868ed-a
 - Spicetify version 2.5.0
 - Dribbblish

**Comment by hewnly** [comment]
yep i've been having the same problem too

**Comment by Soft-Bred** [comment]
same problem here

**Comment by ajhawkings** [comment]
Same thing is happening in JulienMaille/dribbblish-dynamic-theme#16

**Comment by JulienMaille** [comment]
has to do with the absolute positioning in `user.css`
```css
.playback-bar {
    position: absolute;
    width: var(--main-view-width);
    left: var(--sidebar-width);
    bottom: calc(var(--main-gap) + var(--bar-height) - 12px / 2);
}
```

**Comment by LuomingXu** [comment]
@JulienMaille 👍

**Comment by schnensch0** [comment]
you can add this to user.css as a temporary fix:
```css
.main-nowPlayingBar-container>div:first-child:nth-last-child(2) .playback-bar {
    bottom: calc(var(--main-gap) + var(--bar-height) + 18px);
}
```
